config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blog_comments
  resources :blog_posts

  root to: 'welcome#index'

  resources :products
end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
  belongs_to :blog_post
  belongs_to :user

  validates :blog_post, presence: true
  validates :user, presence: true
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence: true
    validates :user, presence: true
    
    has_many :blog_comments, dependent: :destroy
    belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :blog_posts
  has_many :blog_comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  before_action :set_blog_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /blog_comments
  # GET /blog_comments.json
  def index
    @blog_comments = BlogComment.all
  end

  # GET /blog_comments/1
  # GET /blog_comments/1.json
  def show
  end

  # GET /blog_comments/new
  def new
    @blog_comment = BlogComment.new
  end

  # GET /blog_comments/1/edit
  def edit
  end

  # POST /blog_comments
  # POST /blog_comments.json
  def create
    @blog_comment = BlogComment.new(blog_comment_params)
    @blog_comment.user = current_user

    respond_to do |format|
      if @blog_comment.save
        format.html { redirect_to @blog_comment.blog_post, notice: 'Blog comment was successfully created.' }
        format.json { render :show, status: :created, location: @blog_comment }
      else
        format.html { redirect_to @blog_comment.blog_post }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_comments/1
  # PATCH/PUT /blog_comments/1.json
  def update
    respond_to do |format|
      if @blog_comment.update(blog_comment_params)
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_comment }
      else
        format.html { render :edit }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_comments/1
  # DELETE /blog_comments/1.json
  def destroy
    @blog_comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_comments_url, notice: 'Blog comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_comment
      @blog_comment = BlogComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_comment_params
      params.require(:blog_comment).permit(:body, :blog_post_id)
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :validate_ownership!, only: [:edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all.order(created_at: :desc)
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_comment = BlogComment.new
    @blog_comment.blog_post = @blog_post
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.user = current_user

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end
    
    def validate_ownership!
      if @blog_post.user != current_user
        redirect_to @blog_post, notice: "No puedes ejecutar esta acción porque el post no te pertenece."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :cost, :available)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @time = Time.now
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/blog_comments/_form.html.erb
<%= form_for(@blog_comment) do |f| %>
  <% if @blog_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>

      <ul>
      <% @blog_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :blog_post_id %><br>
    <%= f.text_field :blog_post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_comments/edit.html.erb
<h1>Editing Blog Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_comment %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blog Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th>Blog post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_comments.each do |blog_comment| %>
      <tr>
        <td><%= blog_comment.user %></td>
        <td><%= blog_comment.body %></td>
        <td><%= blog_comment.blog_post %></td>
        <td><%= link_to 'Show', blog_comment %></td>
        <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
        <td><%= link_to 'Destroy', blog_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog comment', new_blog_comment_path %>

app/views/blog_comments/new.html.erb
<h1>New Blog Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog_comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog_comment.body %>
</p>

<p>
  <strong>Blog post:</strong>
  <%= @blog_comment.blog_post %>
</p>

<%= link_to 'Edit', edit_blog_comment_path(@blog_comment) %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post, html: { onsubmit: "return validateForm()", name: "CreateBlogPostForm" }) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  function validateForm() {
    var title = document.getElementById("blog_post_title").value;
    var content = document.getElementById("blog_post_content").value;
    if (title.length === 0 || content.length === 0) {
      alert("El título y contenido no puede estar vacío.");
      return false;
    } else {
      return true;
    }
  }
</script>

app/views/blog_posts/edit.html.erb
<div class="container">
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>
</div>

app/views/blog_posts/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Blog posts</h1>

<hr />

<div class="row">
  <% if @blog_posts.empty? %>
    <div class="col-xs-12">
      <p>
        No hay posts hasta el momento.
      </p>  
    </div>
  <% end %>
  
  <% @blog_posts.each do |blog_post| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= blog_post.created_at %>
        </div>
        
        <div class="panel-body">
          <h2><%= blog_post.title %></h2>
          <p><%= blog_post.content %></p>
        </div>
        
        <div class="panel-footer">
          <td><%= link_to 'Ver más', blog_post %></td>
          <% if blog_post.user == current_user %>
            <td><%= link_to 'Editar', edit_blog_post_path(blog_post) %></td>
            <td><%= link_to 'Borrar', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
          <% end %>
        </div>
      </div>
    </div>
  <% end %>  
</div>

<hr />

<% if user_signed_in? %>
  <%= link_to 'Publicar nuevo post', new_blog_post_path, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/blog_posts/new.html.erb
<div class="container">
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>
    
</div>

app/views/blog_posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h1>
    <%= @blog_post.title %>
  </h1>
  
  <p class="lead">
    Autor: <%= @blog_post.user.email %>
  </p>
  
  <p>
    <%= @blog_post.content %>
  </p>
  
  <% if @blog_post.user == current_user %>
    <%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
  <% end %>
  <%= link_to 'Back', blog_posts_path %>
  
  <hr />
  
  <div>
    <% @blog_post.blog_comments.each do |comment| %>
      <div>
        <h3>
          <%= comment.user.email %>
        </h3>
        <p>
          <%= comment.body %>
        </p>
      </div>
    <% end %>
  </div>
  
  <% if user_signed_in? %>
    <div>
      <%= form_for(@blog_comment) do |f| %>
        <% if @blog_comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>
      
            <ul>
            <% @blog_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="field">
          <%= f.label :body %><br>
          <%= f.text_area :body %>
        </div>
        <div class="field">
          <%= f.hidden_field :blog_post_id %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <%= link_to "Blog", blog_posts_path %>
      </li>
      <li>
        <a href="/">Contacto</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <p class="navbar-text">
            Bienvenido <%= current_user.email %>    
          </p>  
        </li>
        <li>
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Iniciar sesión", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Crear cuenta", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Products</h1>
  
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Cost</th>
        <th>Available</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.cost %></td>
          <td><%= product.available %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Product', new_product_path %>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>¿Está disponible?</strong>
  <%= @product.available %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Volver', products_path %>
  
</div>

app/views/welcome/index.html.erb
<div class="container">
    <h1 class="welcome-title">
        Bienvenido!
    </h1>
    <p>
        La hora actual es: <%= @time %>
    </p>
</div>